services:
  postgres1:
    container_name: postgres1
    restart: always
    build: 
      context: ./
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
  postgres2:
    container_name: postgres2
    restart: always
    build: 
      context: ./
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
  postgres3:
    container_name: postgres3
    restart: always
    build: 
      context: ./
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
